### ISSUE TITLE
how to get memory slot total number?

### ISSUE THREAD

**Issue by BiaoGe2399** [saibulusu/SMBIOS-Parser#1]
This is the most perfect SMBIOS table parser code I have ever seen, very good!

**Comment by BiaoGe2399** [comment]
Do you know how to get the total number of memory slots?

**Comment by saibulusu** [comment]
Hey @BiaoGe2399,

I believe that would be in structure 16 (Physical memory array) and it should be called "Number of Memory Devices".

**Comment by BiaoGe2399** [comment]
@saibulusu  I see this "Number of Memory Devices",but it is always 0.My Machine have four memory slots,the windows task manager also shows four slots.
![image](https://user-images.githubusercontent.com/44275365/181669449-5b7efe1d-cafa-4bdd-8108-406c17db123c.png)

**Comment by BiaoGe2399** [comment]
Type 17 occurs four times. Among the unused slots, the size is 0. At present, I can judge the total number of slots and the number of used slots through it.

**Comment by saibulusu** [comment]
@BiaoGe2399 that's interesting. You are right it should show 4 if there are 4 structures of type 17 as you said. Looking into it.
